// <auto-generated />
using System;
using ForkOlympics.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ForkOlympics.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523010400_AddAuthorTitle")]
    partial class AddAuthorTitle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForkOlympics.Web.Data.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarStorageKey")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tagline")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("ForkOlympics.Web.Data.ContentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ContentItems");
                });

            modelBuilder.Entity("ForkOlympics.Web.Data.ContentItemTag", b =>
                {
                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("ContentItemId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ContentItemTags");
                });

            modelBuilder.Entity("ForkOlympics.Web.Data.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .HasColumnType("text");

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StepId")
                        .HasColumnType("uuid");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId");

                    b.HasIndex("StepId");

                    b.ToTable("MediaAssets");
                });

            modelBuilder.Entity("ForkOlympics.Web.Data.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Backstory")
                        .HasColumnType("text");

                    b.Property<Guid>("ContentItemId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CookMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Headnote")
                        .HasColumnType("text");

                    b.Property<int?>("PrepMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("WhyItWorks")
                        .HasColumnType("text");

                    b.Property<string>("Yield")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId")
                        .IsUnique();

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("ForkOlympics.Web.Data.RecipeIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GroupLabel")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrepNote")
                        .HasColumnType("text");

                    b.Property<string>("Quantity")
                        .HasColumnType("text");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("ForkOlympics.Web.Data.RecipeStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RecipeId")
                        .HasColumnType("uuid");

                    b.Property<string>("SectionHeader")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeSteps");
                });

            modelBuilder.Entity("ForkOlympics.Web.Data.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ForkOlympics.Web.Data.ContentItem", b =>
                {
                    b.HasOne("ForkOlympics.Web.Data.Author", "Author")
                        .WithMany("ContentItems")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ForkOlympics.Web.Data.ContentItemTag", b =>
                {
                    b.HasOne("ForkOlympics.Web.Data.ContentItem", "ContentItem")
                        .WithMany("ContentItemTags")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForkOlympics.Web.Data.Tag", "Tag")
                        .WithMany("ContentItemTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentItem");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ForkOlympics.Web.Data.MediaAsset", b =>
                {
                    b.HasOne("ForkOlympics.Web.Data.ContentItem", "ContentItem")
                        .WithMany("MediaAssets")
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForkOlympics.Web.Data.RecipeStep", "Step")
                        .WithMany("MediaAssets")
                        .HasForeignKey("StepId");

                    b.Navigation("ContentItem");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("ForkOlympics.Web.Data.Recipe", b =>
                {
                    b.HasOne("ForkOlympics.Web.Data.ContentItem", "ContentItem")
                        .WithOne("Recipe")
                        .HasForeignKey("ForkOlympics.Web.Data.Recipe", "ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentItem");
                });

            modelBuilder.Entity("ForkOlympics.Web.Data.RecipeIngredient", b =>
                {
                    b.HasOne("ForkOlympics.Web.Data.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ForkOlympics.Web.Data.RecipeStep", b =>
                {
                    b.HasOne("ForkOlympics.Web.Data.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ForkOlympics.Web.Data.Author", b =>
                {
                    b.Navigation("ContentItems");
                });

            modelBuilder.Entity("ForkOlympics.Web.Data.ContentItem", b =>
                {
                    b.Navigation("ContentItemTags");

                    b.Navigation("MediaAssets");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ForkOlympics.Web.Data.Recipe", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("ForkOlympics.Web.Data.RecipeStep", b =>
                {
                    b.Navigation("MediaAssets");
                });

            modelBuilder.Entity("ForkOlympics.Web.Data.Tag", b =>
                {
                    b.Navigation("ContentItemTags");
                });
#pragma warning restore 612, 618
        }
    }
}
